
import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jumnert
 */
public class CafePos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CafePos.class.getName());

    /**
     * Creates new form CafePos
     */
    public CafePos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hotMatchalatte = new javax.swing.JButton();
        Jbtnicelemontea = new javax.swing.JButton();
        hotlatte = new javax.swing.JButton();
        icecoffee = new javax.swing.JButton();
        btnIceAmericano = new javax.swing.JButton();
        jbtnMangoFrape = new javax.swing.JButton();
        jbtnStrawberryFrape = new javax.swing.JButton();
        jbtnLemonea = new javax.swing.JButton();
        jbtncaramaldrink = new javax.swing.JButton();
        jbtnIceMatchaLatte = new javax.swing.JButton();
        jbtnHamBurger = new javax.swing.JButton();
        jbtnjaozi = new javax.swing.JButton();
        jbtnNoodle = new javax.swing.JButton();
        jbtnFriesChicken = new javax.swing.JButton();
        jbtnRiceWithPork = new javax.swing.JButton();
        jbtnTiramisu = new javax.swing.JButton();
        jbtncakeroll = new javax.swing.JButton();
        jbtnPudding = new javax.swing.JButton();
        jbtnblueBerrycake = new javax.swing.JButton();
        jbtnChocolateCake = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbtn9 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtnDot = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtDisplay = new javax.swing.JTextField();
        jtxtChange = new javax.swing.JTextField();
        jcbopayment = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jbtnPay = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnRemove = new javax.swing.JButton();
        jtxtBarCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hotMatchalatte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hotMatchalatte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hotmatcha.jpg"))); // NOI18N
        hotMatchalatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotMatchalatteActionPerformed(evt);
            }
        });
        jPanel1.add(hotMatchalatte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 130));

        Jbtnicelemontea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Jbtnicelemontea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hottea.jpg"))); // NOI18N
        Jbtnicelemontea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnicelemonteaActionPerformed(evt);
            }
        });
        jPanel1.add(Jbtnicelemontea, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 130, 130));

        hotlatte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hotlatte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hotlate.jpg"))); // NOI18N
        hotlatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotlatteActionPerformed(evt);
            }
        });
        jPanel1.add(hotlatte, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 130, 130));

        icecoffee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        icecoffee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/milktea.jpg"))); // NOI18N
        icecoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icecoffeeActionPerformed(evt);
            }
        });
        jPanel1.add(icecoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 130, 130));

        btnIceAmericano.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIceAmericano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/IceAmericano.jpg"))); // NOI18N
        btnIceAmericano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIceAmericanoActionPerformed(evt);
            }
        });
        jPanel1.add(btnIceAmericano, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 130, 130));

        jbtnMangoFrape.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnMangoFrape.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mangofrape.jpg"))); // NOI18N
        jbtnMangoFrape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMangoFrapeActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnMangoFrape, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 130, 130));

        jbtnStrawberryFrape.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnStrawberryFrape.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/strawbeeryfrape.jpg"))); // NOI18N
        jbtnStrawberryFrape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnStrawberryFrapeActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnStrawberryFrape, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 130, 130));

        jbtnLemonea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnLemonea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/lemonea.jpg"))); // NOI18N
        jbtnLemonea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLemoneaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnLemonea, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 130, 130));

        jbtncaramaldrink.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtncaramaldrink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/camramelFrape.jpg"))); // NOI18N
        jbtncaramaldrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncaramaldrinkActionPerformed(evt);
            }
        });
        jPanel1.add(jbtncaramaldrink, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 130, 130));

        jbtnIceMatchaLatte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnIceMatchaLatte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icematchalatte.jpg"))); // NOI18N
        jbtnIceMatchaLatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIceMatchaLatteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnIceMatchaLatte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 130, 130));

        jbtnHamBurger.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnHamBurger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/burger.jpg"))); // NOI18N
        jbtnHamBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHamBurgerActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnHamBurger, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 130, 130));

        jbtnjaozi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnjaozi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/jouzi.jpg"))); // NOI18N
        jbtnjaozi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnjaoziActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnjaozi, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 130, 130));

        jbtnNoodle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnNoodle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/noodel.jpg"))); // NOI18N
        jbtnNoodle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNoodleActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnNoodle, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 130, 130));

        jbtnFriesChicken.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnFriesChicken.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chicken.jpg"))); // NOI18N
        jbtnFriesChicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFriesChickenActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnFriesChicken, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 130, 130));

        jbtnRiceWithPork.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnRiceWithPork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rice.jpg"))); // NOI18N
        jbtnRiceWithPork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRiceWithPorkActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnRiceWithPork, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 130, 130));

        jbtnTiramisu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnTiramisu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tiramisu.jpg"))); // NOI18N
        jbtnTiramisu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTiramisuActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnTiramisu, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 130, 130));

        jbtncakeroll.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtncakeroll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/matchacake.jpg"))); // NOI18N
        jbtncakeroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncakerollActionPerformed(evt);
            }
        });
        jPanel1.add(jbtncakeroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 130, 130));

        jbtnPudding.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnPudding.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pudding.jpg"))); // NOI18N
        jbtnPudding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPuddingActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPudding, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 130, 130));

        jbtnblueBerrycake.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnblueBerrycake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/blueberrycake.jpg"))); // NOI18N
        jbtnblueBerrycake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnblueBerrycakeActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnblueBerrycake, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 130, 130));

        jbtnChocolateCake.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnChocolateCake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chocolatecake.jpg"))); // NOI18N
        jbtnChocolateCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChocolateCakeActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnChocolateCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 130, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 710, 570));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 80, 80));

        jbtn7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 80));

        jbtn8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 80, 80));

        jbtn4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, 80));

        jbtn5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 80, 80));

        jbtn6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 80, 80));

        jbtnDot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnDot.setText(".");
        jbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDotActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 80, 80));

        jbtnC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnC.setText("C");
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 80, 80));

        jbtn0.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 80, 80));

        jbtn3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 80, 80));

        jbtn2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 80, 80));

        jbtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 80, 80));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 300, 570));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantiity", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 370, 510));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 700, -1, -1));

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setPreferredSize(new java.awt.Dimension(170, 104));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Total");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setText("SubTotal");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel3.setText("Tax");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jtxtTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel4.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 180, -1));

        jtxtSubTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel4.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 180, -1));

        jtxtTax.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel4.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 180, -1));

        jPanel12.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 160));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setPreferredSize(new java.awt.Dimension(170, 104));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel7.setText("Change");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel8.setText("Cash");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel9.setText("Payment Method");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jtxtDisplay.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel5.add(jtxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 170, -1));

        jtxtChange.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel5.add(jtxtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 170, -1));

        jcbopayment.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jcbopayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Visa Card", "Master Card", " " }));
        jcbopayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbopaymentActionPerformed(evt);
            }
        });
        jPanel5.add(jcbopayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 170, 40));

        jPanel12.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 480, 160));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setPreferredSize(new java.awt.Dimension(170, 104));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnPay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnPay.setText("PAY");
        jbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPayActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 140));

        jbtnExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnExit.setText("EXIT");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 260, 60));

        jbtnPrint.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.setMaximumSize(new java.awt.Dimension(129, 35));
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 80, 70));

        jbtnReset.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.setMaximumSize(new java.awt.Dimension(129, 35));
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 80, 70));

        jbtnRemove.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnRemove.setText("Remove");
        jbtnRemove.setMaximumSize(new java.awt.Dimension(129, 35));
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 80, 70));

        jPanel12.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 440, 160));

        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 1400, 180));

        jtxtBarCode.setFont(new java.awt.Font("IDAutomationHC39M Free Version", 0, 14)); // NOI18N
        jtxtBarCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBarCodeActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtBarCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, 370, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//Function.,,,,,,
    public void ItemCost(){
        double sum = 0;
        for (int i = 0;i < jTable1.getRowCount();i++){
            sum += Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        jtxtSubTotal.setText(Double.toString(sum));
        double cTOtal1 =  Double.parseDouble(jtxtSubTotal.getText());
        double cTax = (cTOtal1  * 3.9)/100;
        
        String iTaxTotal  = String.format("$ %.2f", cTax);
        jtxtTax.setText(iTaxTotal);
        
        String iSubTotal  = String.format("$ %.2f", cTOtal1);
        jtxtSubTotal.setText(iSubTotal);
        
        String iTotal  = String.format("$ %.2f", cTOtal1 + cTax);
        jtxtTotal.setText(iTotal);
        
        
        String BarCode  = String.format("Total is $ %.2f", cTOtal1 + cTax);
        jtxtBarCode.setText(BarCode);
        
    }
    
    
    //function change////
    public void Change(){
        double sum = 0;
        double tax= 3.9;
        double cash = Double.parseDouble(jtxtDisplay.getText());
        
        
          for (int i = 0;i < jTable1.getRowCount();i++)
        {
            sum += Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
          
          double cTax = (sum  * 3.9)/100;
          double cChange = (cash - (sum + cTax));
          
          
          String ChangeGiven = String.format("$ %.2f",cChange);
          jtxtChange.setText(ChangeGiven);
        
    }
    
    private void jcbopaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbopaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbopaymentActionPerformed

    private void jtxtBarCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBarCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBarCodeActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jtxtDisplay.getText();
    if (Enternumber.equals("")) {
        jtxtDisplay.setText(jbtn2.getText());
    } else {
        Enternumber = Enternumber + jbtn2.getText();
        jtxtDisplay.setText(Enternumber);
    }
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDotActionPerformed
        // TODO add your handling code here:
        String Enternumber = jtxtDisplay.getText();

    // Prevent multiple dots
    if (!Enternumber.contains(".")) {
        if (Enternumber.equals("")) {
            jtxtDisplay.setText("0.");
        } else {
            jtxtDisplay.setText(Enternumber + ".");
        }
    }
    }//GEN-LAST:event_jbtnDotActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
       String Enternumber = jtxtDisplay.getText();
       if(Enternumber == ""){
           jtxtDisplay.setText(jbtn7.getText());
       }
       else{
           Enternumber = jtxtDisplay.getText() + jbtn7.getText();
           jtxtDisplay.setText(Enternumber);
       }
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jtxtDisplay.getText();
    if (Enternumber.equals("")) {
        jtxtDisplay.setText(jbtn8.getText());
    } else {
        Enternumber = Enternumber + jbtn8.getText();
        jtxtDisplay.setText(Enternumber);
    }
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        // TODO add your handling code here:
         String Enternumber = jtxtDisplay.getText();
    if (Enternumber.equals("")) {
        jtxtDisplay.setText(jbtn9.getText());
    } else {
        Enternumber = Enternumber + jbtn9.getText();
        jtxtDisplay.setText(Enternumber);
    }
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        // TODO add your handling code here:
          String Enternumber = jtxtDisplay.getText();
    if (Enternumber.equals("")) {
        jtxtDisplay.setText(jbtn4.getText());
    } else {
        Enternumber = Enternumber + jbtn4.getText();
        jtxtDisplay.setText(Enternumber);
    }
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        // TODO add your handling code here:
         String Enternumber = jtxtDisplay.getText();
    if (Enternumber.equals("")) {
        jtxtDisplay.setText(jbtn5.getText());
    } else {
        Enternumber = Enternumber + jbtn5.getText();
        jtxtDisplay.setText(Enternumber);
    }
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        // TODO add your handling code here:
         String Enternumber = jtxtDisplay.getText();
    if (Enternumber.equals("")) {
        jtxtDisplay.setText(jbtn6.getText());
    } else {
        Enternumber = Enternumber + jbtn6.getText();
        jtxtDisplay.setText(Enternumber);
    }
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        // TODO add your handling code here:
         String Enternumber = jtxtDisplay.getText();
    if (Enternumber.equals("")) {
        jtxtDisplay.setText(jbtn1.getText());
    } else {
        Enternumber = Enternumber + jbtn1.getText();
        jtxtDisplay.setText(Enternumber);
    }
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        // TODO add your handling code here:
          String Enternumber = jtxtDisplay.getText();
    if (Enternumber.equals("")) {
        jtxtDisplay.setText(jbtn3.getText());
    } else {
        Enternumber = Enternumber + jbtn3.getText();
        jtxtDisplay.setText(Enternumber);
    }
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jtxtDisplay.getText();
    if (Enternumber.equals("")) {
        jtxtDisplay.setText(jbtn0.getText());
    } else {
        Enternumber = Enternumber + jbtn0.getText();
        jtxtDisplay.setText(Enternumber);
    }
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        // TODO add your handling code here:
          jtxtDisplay.setText("");
            jtxtChange.setText("");
    }//GEN-LAST:event_jbtnCActionPerformed

    private void jbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPayActionPerformed
        // TODO add your handling code here:
        if(jcbopayment.getSelectedItem().equals("Cash"))
        {
            Change();
        }else{
        jtxtChange.setText("");
        jtxtDisplay.setText("");
         }
        
    }//GEN-LAST:event_jbtnPayActionPerformed

    private void hotMatchalatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotMatchalatteActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 3.00;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Hot matcha latte","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_hotMatchalatteActionPerformed

    private void jbtncaramaldrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncaramaldrinkActionPerformed
        // TODO add your handling code here:
        
        double PriceOfItem = 3.50;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"caramel coffee","1",PriceOfItem });
        ItemCost();
        
    }//GEN-LAST:event_jbtncaramaldrinkActionPerformed

    private void jbtnIceMatchaLatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIceMatchaLatteActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 3.50;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Ice Matcha Latte","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnIceMatchaLatteActionPerformed

    private void hotlatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotlatteActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 2.5;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"caramel coffee","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_hotlatteActionPerformed

    private void icecoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icecoffeeActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 1.75;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"ice coffee","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_icecoffeeActionPerformed

    private void btnIceAmericanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIceAmericanoActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 1.50;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Ice Americano","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_btnIceAmericanoActionPerformed

    private void JbtnicelemonteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnicelemonteaActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 1.00;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Ice Lemon tea","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_JbtnicelemonteaActionPerformed

    private void jbtnLemoneaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLemoneaActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 1.85;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Ice Lemon Tea","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnLemoneaActionPerformed

    private void jbtnStrawberryFrapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnStrawberryFrapeActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 3.50;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Strawberry Frape","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnStrawberryFrapeActionPerformed

    private void jbtnMangoFrapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMangoFrapeActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 3.25;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Mango Frape","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnMangoFrapeActionPerformed

    private void jbtnRiceWithPorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRiceWithPorkActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 3.50;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Rice With Fries Pork","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnRiceWithPorkActionPerformed

    private void jbtnFriesChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFriesChickenActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 5.00;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"set of Fries Chichen","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnFriesChickenActionPerformed

    private void jbtnNoodleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNoodleActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 2.35;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Noodle","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnNoodleActionPerformed

    private void jbtnjaoziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnjaoziActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 3.25;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Jao Zi","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnjaoziActionPerformed

    private void jbtnHamBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHamBurgerActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 3.00;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Chicken Humberger","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnHamBurgerActionPerformed

    private void jbtnChocolateCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChocolateCakeActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 3.75;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Chocolate cake","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnChocolateCakeActionPerformed

    private void jbtnblueBerrycakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnblueBerrycakeActionPerformed
        // TODO add your handling code here:
         double PriceOfItem = 3.75;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Blueberry cake","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnblueBerrycakeActionPerformed

    private void jbtnTiramisuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTiramisuActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 3.75;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Tiramisu cake","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnTiramisuActionPerformed

    private void jbtncakerollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncakerollActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 3.00;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Matcha cake Roll","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtncakerollActionPerformed

    private void jbtnPuddingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPuddingActionPerformed
        // TODO add your handling code here:  double PriceOfItem = 3.75;
        
        double PriceOfItem = 2.00;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Pudding cake","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnPuddingActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
        
         
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        jtxtChange.setText("");
        jtxtTax.setText("");
        jtxtTotal.setText("");
        jtxtSubTotal.setText("");
        jtxtDisplay.setText("");
        jtxtBarCode.setText("");
        
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Printing in the progress");
        MessageFormat footer = new MessageFormat("page {0,  number, integer}");
        
        try{
            jTable1.print(JTable.PrintMode.NORMAL, header, footer);
        }
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("No Printer found", e.getMessage());
        }
        
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
         
         int RemoveItem = jTable1.getSelectedRow();
         if(RemoveItem > 0 ){
             model.removeRow(RemoveItem);
         }
         ItemCost();
         
         if(jcbopayment.getSelectedItem().equals("Cash"))
         {
             Change();
         }else{
              jtxtDisplay.setText("");
            jtxtChange.setText("");
         }
         
    }//GEN-LAST:event_jbtnRemoveActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("{Exit");
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit", "Point of sales",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_jbtnExitActionPerformed
     
    private JFrame frame;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CafePos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtnicelemontea;
    private javax.swing.JButton btnIceAmericano;
    private javax.swing.JButton hotMatchalatte;
    private javax.swing.JButton hotlatte;
    private javax.swing.JButton icecoffee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnChocolateCake;
    private javax.swing.JButton jbtnDot;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnFriesChicken;
    private javax.swing.JButton jbtnHamBurger;
    private javax.swing.JButton jbtnIceMatchaLatte;
    private javax.swing.JButton jbtnLemonea;
    private javax.swing.JButton jbtnMangoFrape;
    private javax.swing.JButton jbtnNoodle;
    private javax.swing.JButton jbtnPay;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnPudding;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnRiceWithPork;
    private javax.swing.JButton jbtnStrawberryFrape;
    private javax.swing.JButton jbtnTiramisu;
    private javax.swing.JButton jbtnblueBerrycake;
    private javax.swing.JButton jbtncakeroll;
    private javax.swing.JButton jbtncaramaldrink;
    private javax.swing.JButton jbtnjaozi;
    private javax.swing.JComboBox<String> jcbopayment;
    private javax.swing.JTextField jtxtBarCode;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
