import java.sql.*;
import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.UIManager;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import com.formdev.flatlaf.FlatDarkLaf;
import java.sql.*;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.table.DefaultTableModel;
import java.awt.Font;
import java.awt.print.PrinterException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import java.text.MessageFormat;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import javax.swing.*;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.function.BiConsumer;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;





/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jumnert
 */
public class CafePos extends javax.swing.JFrame  {
    PDType1Font font = PDType1Font.HELVETICA;
final float[] yPos = {750f};
    private ItemManager itemManager = new ItemManager();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CafePos.class.getName());
    //logger
    /**
     * Creates new form CafePos
     */
    public CafePos() {
          initComponents();
            showDate();
    }
    private void showDate() {
    java.time.LocalDate today = java.time.LocalDate.now();
    java.time.format.DateTimeFormatter fmt =
            java.time.format.DateTimeFormatter.ofPattern("MMMM dd, yyyy");

    jlblDate.setText(today.format(fmt));
}
    
public class DBConnection {
    private static final String URL = "jdbc:mysql://localhost:3306/cafepos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true";
    private static final String USER = "root";
    private static final String PASS = "nith2020";
    public static Connection getConnection() throws SQLException {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        return DriverManager.getConnection(URL, USER, PASS);
    }
}

private OrderManager orderManager = new OrderManager();


private double calculateTotal(DefaultTableModel model){
    double sum = 0;
    for(int i = 0; i < model.getRowCount(); i++){
        sum += Double.parseDouble(model.getValueAt(i, 2).toString());
    }
    return sum + (sum * 0.039); // including tax
}

private int getItemId(String name, double price){
    int id = 0;
    try (Connection conn = DBConnection.getConnection()) {
        PreparedStatement pst = conn.prepareStatement("SELECT item_id FROM items WHERE name=?");
        pst.setString(1, name);
        ResultSet rs = pst.executeQuery();
        if(rs.next()) {
            id = rs.getInt("item_id");
        } else {
            // Item does not exist, optionally insert it
            PreparedStatement insert = conn.prepareStatement(
                "INSERT INTO items(name, price) VALUES(?, ?) ", Statement.RETURN_GENERATED_KEYS);
            insert.setString(1, name);
            insert.setDouble(2, price);; // default price 0 if unknown
            insert.executeUpdate();
            ResultSet keys = insert.getGeneratedKeys();
            if(keys.next()) id = keys.getInt(1);
        }
    } catch(SQLException e){
        e.printStackTrace();
    }
    return id;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hotMatchalatte = new javax.swing.JButton();
        Jbtnicelemontea = new javax.swing.JButton();
        hotlatte = new javax.swing.JButton();
        icecoffee = new javax.swing.JButton();
        btnIceAmericano = new javax.swing.JButton();
        jbtnMangoFrape = new javax.swing.JButton();
        jbtnStrawberryFrape = new javax.swing.JButton();
        jbtnLemonea = new javax.swing.JButton();
        jbtncaramaldrink = new javax.swing.JButton();
        jbtnIceMatchaLatte = new javax.swing.JButton();
        jbtnHamBurger = new javax.swing.JButton();
        jbtnjaozi = new javax.swing.JButton();
        jbtnNoodle = new javax.swing.JButton();
        jbtnFriesChicken = new javax.swing.JButton();
        jbtnRiceWithPork = new javax.swing.JButton();
        jbtnTiramisu = new javax.swing.JButton();
        jbtncakeroll = new javax.swing.JButton();
        jbtnPudding = new javax.swing.JButton();
        jbtnblueBerrycake = new javax.swing.JButton();
        jbtnChocolateCake = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbtn9 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtnDot = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jtxtBarCode = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jbtnPay = new javax.swing.JButton();
        jbtnRemove = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jlblDate = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtDisplay = new javax.swing.JTextField();
        jcbopayment = new javax.swing.JComboBox<>();
        jtxtChange = new javax.swing.JTextField();
        jbtnExit = new javax.swing.JButton();
        jbtnDashboard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hotMatchalatte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hotMatchalatte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hotmatcha.jpg"))); // NOI18N
        hotMatchalatte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hotMatchalatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotMatchalatteActionPerformed(evt);
            }
        });
        jPanel1.add(hotMatchalatte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 130, 130));

        Jbtnicelemontea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Jbtnicelemontea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hottea.jpg"))); // NOI18N
        Jbtnicelemontea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnicelemonteaActionPerformed(evt);
            }
        });
        jPanel1.add(Jbtnicelemontea, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 130, 130));

        hotlatte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hotlatte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hotlate.jpg"))); // NOI18N
        hotlatte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hotlatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotlatteActionPerformed(evt);
            }
        });
        jPanel1.add(hotlatte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 130));

        icecoffee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        icecoffee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/milktea.jpg"))); // NOI18N
        icecoffee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icecoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icecoffeeActionPerformed(evt);
            }
        });
        jPanel1.add(icecoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 130, 130));

        btnIceAmericano.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIceAmericano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/IceAmericano.jpg"))); // NOI18N
        btnIceAmericano.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIceAmericano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIceAmericanoActionPerformed(evt);
            }
        });
        jPanel1.add(btnIceAmericano, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 130, 130));

        jbtnMangoFrape.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnMangoFrape.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mangofrape.jpg"))); // NOI18N
        jbtnMangoFrape.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnMangoFrape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMangoFrapeActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnMangoFrape, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 130, 130));

        jbtnStrawberryFrape.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnStrawberryFrape.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/strawbeeryfrape.jpg"))); // NOI18N
        jbtnStrawberryFrape.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnStrawberryFrape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnStrawberryFrapeActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnStrawberryFrape, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 130, 130));

        jbtnLemonea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnLemonea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/lemonea.jpg"))); // NOI18N
        jbtnLemonea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnLemonea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLemoneaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnLemonea, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 130, 130));

        jbtncaramaldrink.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtncaramaldrink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/camramelFrape.jpg"))); // NOI18N
        jbtncaramaldrink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtncaramaldrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncaramaldrinkActionPerformed(evt);
            }
        });
        jPanel1.add(jbtncaramaldrink, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 130, 130));

        jbtnIceMatchaLatte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnIceMatchaLatte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icematchalatte.jpg"))); // NOI18N
        jbtnIceMatchaLatte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnIceMatchaLatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIceMatchaLatteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnIceMatchaLatte, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 570, 130, 130));

        jbtnHamBurger.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnHamBurger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/burger.jpg"))); // NOI18N
        jbtnHamBurger.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnHamBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHamBurgerActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnHamBurger, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 130, 130));

        jbtnjaozi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnjaozi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/jouzi.jpg"))); // NOI18N
        jbtnjaozi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnjaozi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnjaoziActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnjaozi, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 130, 130));

        jbtnNoodle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnNoodle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/noodel.jpg"))); // NOI18N
        jbtnNoodle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnNoodle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNoodleActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnNoodle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 130, 130));

        jbtnFriesChicken.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnFriesChicken.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chicken.jpg"))); // NOI18N
        jbtnFriesChicken.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnFriesChicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFriesChickenActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnFriesChicken, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 130, 130));

        jbtnRiceWithPork.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnRiceWithPork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rice.jpg"))); // NOI18N
        jbtnRiceWithPork.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnRiceWithPork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRiceWithPorkActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnRiceWithPork, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 570, 130, 130));

        jbtnTiramisu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnTiramisu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tiramisu.jpg"))); // NOI18N
        jbtnTiramisu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnTiramisu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTiramisuActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnTiramisu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 130, 130));

        jbtncakeroll.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtncakeroll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/matchacake.jpg"))); // NOI18N
        jbtncakeroll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtncakeroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncakerollActionPerformed(evt);
            }
        });
        jPanel1.add(jbtncakeroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 130, 130));

        jbtnPudding.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnPudding.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pudding.jpg"))); // NOI18N
        jbtnPudding.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPudding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPuddingActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPudding, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 130, 130));

        jbtnblueBerrycake.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnblueBerrycake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/blueberrycake.jpg"))); // NOI18N
        jbtnblueBerrycake.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnblueBerrycake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnblueBerrycakeActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnblueBerrycake, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 130, 130));

        jbtnChocolateCake.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnChocolateCake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chocolatecake.jpg"))); // NOI18N
        jbtnChocolateCake.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnChocolateCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChocolateCakeActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnChocolateCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 570, 130, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 570, 710));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn9.setText("9");
        jbtn9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 80, 80));

        jbtn7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn7.setText("7");
        jbtn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 80));

        jbtn8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn8.setText("8");
        jbtn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 80, 80));

        jbtn4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn4.setText("4");
        jbtn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 80, 80));

        jbtn5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn5.setText("5");
        jbtn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 80, 80));

        jbtn6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn6.setText("6");
        jbtn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 80, 80));

        jbtnDot.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnDot.setText(".");
        jbtnDot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDotActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 80, 80));

        jbtnC.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnC.setText("C");
        jbtnC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 80, 80));

        jbtn0.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn0.setText("0");
        jbtn0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 80, 80));

        jbtn3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn3.setText("3");
        jbtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 80, 80));

        jbtn2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn2.setText("2");
        jbtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 80, 80));

        jbtn1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtn1.setText("1");
        jbtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 80, 80));

        jtxtSubTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel2.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 110, -1));

        jtxtTax.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel2.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 110, -1));

        jtxtTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel2.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 110, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("SubTotal");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Tax");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Total");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 300, 530));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantiity", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 120, 370, 490));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 700, -1, -1));

        jtxtBarCode.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jtxtBarCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBarCodeActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtBarCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 610, 370, 60));

        jPanel6.setPreferredSize(new java.awt.Dimension(170, 104));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnPay.setBackground(new java.awt.Color(4, 98, 66));
        jbtnPay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnPay.setForeground(new java.awt.Color(255, 255, 255));
        jbtnPay.setText("PAY");
        jbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPayActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 150));

        jbtnRemove.setBackground(new java.awt.Color(255, 51, 51));
        jbtnRemove.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnRemove.setForeground(new java.awt.Color(255, 255, 255));
        jbtnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/trash.png"))); // NOI18N
        jbtnRemove.setText("Remove");
        jbtnRemove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnRemove.setMaximumSize(new java.awt.Dimension(129, 35));
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 190, 70));

        jbtnReset.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.closePressedBackground"));
        jbtnReset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnReset.setForeground(new java.awt.Color(255, 255, 255));
        jbtnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/reset.png"))); // NOI18N
        jbtnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnReset.setMaximumSize(new java.awt.Dimension(129, 35));
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 80, 70));

        jbtnPrint.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jbtnPrint.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnPrint.setForeground(new java.awt.Color(255, 255, 255));
        jbtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/printer (1).png"))); // NOI18N
        jbtnPrint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPrint.setMaximumSize(new java.awt.Dimension(129, 35));
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 100, 70));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 670, 400, 180));

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("Forest Cafe");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jlblDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel8.add(jlblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, 180, 30));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1180, 70));

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Change");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Payment Method");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 250, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Cash");
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jtxtDisplay.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel9.add(jtxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 110, -1));

        jcbopayment.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jcbopayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Visa Card", "Master Card", "QR Code" }));
        jcbopayment.setToolTipText("");
        jcbopayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbopaymentActionPerformed(evt);
            }
        });
        jPanel9.add(jcbopayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 110, 40));

        jtxtChange.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel9.add(jtxtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 110, -1));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 300, 180));

        jbtnExit.setBackground(new java.awt.Color(255, 51, 0));
        jbtnExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnExit.setForeground(new java.awt.Color(255, 255, 255));
        jbtnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logout.png"))); // NOI18N
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 40, 70, 70));

        jbtnDashboard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtnDashboard.setText("Dashboard");
        jbtnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDashboardActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//Function.,,,,,,
    public void ItemCost(){
         double sum = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum += Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        
        double cTax = (sum * 3.9) / 100;
        double cTotal = sum + cTax;
        
        jtxtSubTotal.setText(String.format("$ %.2f", sum));
        jtxtTax.setText(String.format("$ %.2f", cTax));
        jtxtTotal.setText(String.format("$ %.2f", cTotal));
        jtxtBarCode.setText(String.format("Total is $ %.2f", cTotal));
        
    }
    //function change////
    public void Change(){
        try {
            double sum = 0;
            double cash = Double.parseDouble(jtxtDisplay.getText());
            
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                sum += Double.parseDouble(jTable1.getValueAt(i, 2).toString());
            }
            
            double cTax = (sum * 3.9) / 100;
            double cChange = cash - (sum + cTax);
            
            if (cChange < 0) {
                JOptionPane.showMessageDialog(this, "Insufficient cash payment!", "Error", JOptionPane.ERROR_MESSAGE);
                jtxtChange.setText("$ 0.00");
            } else {
                jtxtChange.setText(String.format("$ %.2f", cChange));
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid cash amount!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void jtxtBarCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBarCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBarCodeActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jtxtDisplay.getText();
    if (Enternumber.equals("")) {
        jtxtDisplay.setText(jbtn2.getText());
    } else {
        Enternumber = Enternumber + jbtn2.getText();
        jtxtDisplay.setText(Enternumber);
    }if (jcbopayment.getSelectedItem().equals("Cash")) {
    Change();
    }//GEN-LAST:event_jbtn2ActionPerformed
    }
    
    private void jbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDotActionPerformed
        // TODO add your handling code here:
        String Enternumber = jtxtDisplay.getText();

    // Prevent multiple dots
    if (!Enternumber.contains(".")) {
        if (Enternumber.equals("")) {
            jtxtDisplay.setText("0.");
        } else {
            jtxtDisplay.setText(Enternumber + ".");
        }
    }if (jcbopayment.getSelectedItem().equals("Cash")) {
    Change();
}
    }//GEN-LAST:event_jbtnDotActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
          String Enternumber = jtxtDisplay.getText();
        if (Enternumber.equals("")) {  // FIXED: was using ==
            jtxtDisplay.setText(jbtn7.getText());
        } else {
            Enternumber = jtxtDisplay.getText() + jbtn7.getText();
            jtxtDisplay.setText(Enternumber);
        }if (jcbopayment.getSelectedItem().equals("Cash")) {
    Change();
}
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jtxtDisplay.getText();
    if (Enternumber.equals("")) {
        jtxtDisplay.setText(jbtn8.getText());
    } else {
        Enternumber = Enternumber + jbtn8.getText();
        jtxtDisplay.setText(Enternumber);
    }if (jcbopayment.getSelectedItem().equals("Cash")) {
    Change();
}
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        // TODO add your handling code here:
         String Enternumber = jtxtDisplay.getText();
    if (Enternumber.equals("")) {
        jtxtDisplay.setText(jbtn9.getText());
    } else {
        Enternumber = Enternumber + jbtn9.getText();
        jtxtDisplay.setText(Enternumber);
    }if (jcbopayment.getSelectedItem().equals("Cash")) {
    Change();
}
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        // TODO add your handling code here:
          String Enternumber = jtxtDisplay.getText();
    if (Enternumber.equals("")) {
        jtxtDisplay.setText(jbtn4.getText());
    } else {
        Enternumber = Enternumber + jbtn4.getText();
        jtxtDisplay.setText(Enternumber);
    }if (jcbopayment.getSelectedItem().equals("Cash")) {
    Change();
}
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        // TODO add your handling code here:
         String Enternumber = jtxtDisplay.getText();
    if (Enternumber.equals("")) {
        jtxtDisplay.setText(jbtn5.getText());
    } else {
        Enternumber = Enternumber + jbtn5.getText();
        jtxtDisplay.setText(Enternumber);
    }if (jcbopayment.getSelectedItem().equals("Cash")) {
    Change();
}
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        // TODO add your handling code here:
         String Enternumber = jtxtDisplay.getText();
    if (Enternumber.equals("")) {
        jtxtDisplay.setText(jbtn6.getText());
    } else {
        Enternumber = Enternumber + jbtn6.getText();
        jtxtDisplay.setText(Enternumber);
    }if (jcbopayment.getSelectedItem().equals("Cash")) {
    Change();
}
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        // TODO add your handling code here:
         String Enternumber = jtxtDisplay.getText();
    if (Enternumber.equals("")) {
        jtxtDisplay.setText(jbtn1.getText());
    } else {
        Enternumber = Enternumber + jbtn1.getText();
        jtxtDisplay.setText(Enternumber);
    }if (jcbopayment.getSelectedItem().equals("Cash")) {
    Change();
}
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        // TODO add your handling code here:
          String Enternumber = jtxtDisplay.getText();
    if (Enternumber.equals("")) {
        jtxtDisplay.setText(jbtn3.getText());
    } else {
        Enternumber = Enternumber + jbtn3.getText();
        jtxtDisplay.setText(Enternumber);
    }if (jcbopayment.getSelectedItem().equals("Cash")) {
    Change();
}
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jtxtDisplay.getText();
    if (Enternumber.equals("")) {
        jtxtDisplay.setText(jbtn0.getText());
    } else {
        Enternumber = Enternumber + jbtn0.getText();
        jtxtDisplay.setText(Enternumber);
    }if (jcbopayment.getSelectedItem().equals("Cash")) {
    Change();
}
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        // TODO add your handling code here:
          jtxtDisplay.setText("");
            jtxtChange.setText("");
    }//GEN-LAST:event_jbtnCActionPerformed

    private void hotMatchalatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotMatchalatteActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 3.00;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Hot matcha latte","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_hotMatchalatteActionPerformed

    private void jbtncaramaldrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncaramaldrinkActionPerformed
        // TODO add your handling code here:
        
        double PriceOfItem = 3.50;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"caramel coffee","1",PriceOfItem });
        ItemCost();
        
    }//GEN-LAST:event_jbtncaramaldrinkActionPerformed

    private void jbtnIceMatchaLatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIceMatchaLatteActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 3.50;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Ice Matcha Latte","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnIceMatchaLatteActionPerformed

    private void hotlatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotlatteActionPerformed
         double PriceOfItem = 2.5;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Hot Latte", "1", PriceOfItem});  // FIXED: was "caramel coffee"
        ItemCost();
    }//GEN-LAST:event_hotlatteActionPerformed

    private void icecoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icecoffeeActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 1.75;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"ice coffee","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_icecoffeeActionPerformed

    private void btnIceAmericanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIceAmericanoActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 1.50;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Ice Americano","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_btnIceAmericanoActionPerformed

    private void JbtnicelemonteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnicelemonteaActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 1.00;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Ice Lemon tea","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_JbtnicelemonteaActionPerformed

    private void jbtnLemoneaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLemoneaActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 1.85;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Ice Lemon Tea","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnLemoneaActionPerformed

    private void jbtnStrawberryFrapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnStrawberryFrapeActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 3.50;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Strawberry Frape","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnStrawberryFrapeActionPerformed

    private void jbtnMangoFrapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMangoFrapeActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 3.25;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Mango Frape","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnMangoFrapeActionPerformed

    private void jbtnRiceWithPorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRiceWithPorkActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 3.50;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Rice With Fries Pork","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnRiceWithPorkActionPerformed

    private void jbtnFriesChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFriesChickenActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 5.00;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"set of Fries Chichen","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnFriesChickenActionPerformed

    private void jbtnNoodleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNoodleActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 2.35;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Noodle","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnNoodleActionPerformed

    private void jbtnjaoziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnjaoziActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 3.25;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Jao Zi","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnjaoziActionPerformed

    private void jbtnHamBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHamBurgerActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 3.00;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Chicken Humberger","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnHamBurgerActionPerformed

    private void jbtnChocolateCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChocolateCakeActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 3.75;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Chocolate cake","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnChocolateCakeActionPerformed

    private void jbtnblueBerrycakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnblueBerrycakeActionPerformed
        // TODO add your handling code here:
         double PriceOfItem = 3.75;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Blueberry cake","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnblueBerrycakeActionPerformed

    private void jbtnTiramisuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTiramisuActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 3.75;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Tiramisu cake","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnTiramisuActionPerformed

    private void jbtncakerollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncakerollActionPerformed
        // TODO add your handling code here:
          double PriceOfItem = 3.00;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Matcha cake Roll","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtncakerollActionPerformed

    private void jbtnPuddingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPuddingActionPerformed
        // TODO add your handling code here:  double PriceOfItem = 3.75;
        
        double PriceOfItem = 2.00;
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Pudding cake","1",PriceOfItem });
        ItemCost();
    }//GEN-LAST:event_jbtnPuddingActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int RemoveItem = jTable1.getSelectedRow();
        
        if (RemoveItem >= 0) {  // FIXED: was > 0, should be >= 0 (row indices start at 0)
            model.removeRow(RemoveItem);
            ItemCost();
            
            if (jcbopayment.getSelectedItem().equals("Cash")) {
                Change();
            } else {
                jtxtDisplay.setText("");
                jtxtChange.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row to remove!", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jbtnRemoveActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        jtxtChange.setText("");
        jtxtTax.setText("");
        jtxtTotal.setText("");
        jtxtSubTotal.setText("");
        jtxtDisplay.setText("");
        jtxtBarCode.setText("");

    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
           try {
        // Choose save location
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save Receipt");
        fileChooser.setSelectedFile(new File("Receipt_" + System.currentTimeMillis() + ".pdf"));
        
        int choice = fileChooser.showSaveDialog(this);
        if (choice != JFileChooser.APPROVE_OPTION) return;

        String filePath = fileChooser.getSelectedFile().getAbsolutePath();
        if (!filePath.toLowerCase().endsWith(".pdf")) {
            filePath += ".pdf";
        }

        // Create PDF
        PDDocument doc = new PDDocument();
        PDPage page = new PDPage(new PDRectangle(226, 600)); // Thermal receipt size (80mm width)
        doc.addPage(page);

        PDPageContentStream content = new PDPageContentStream(doc, page);
        PDType1Font fontBold = PDType1Font.HELVETICA_BOLD;
        PDType1Font fontRegular = PDType1Font.HELVETICA;

        float margin = 20;
        float[] yPos = {570}; // Use array to make it effectively final
        float pageWidth = page.getMediaBox().getWidth();

        // ===== HEADER =====
        yPos[0] -= 10;
        
        // Cafe Name
        content.setFont(fontBold, 12);
        String title = "AMAZON FOREST CAFE";
        float titleWidth = fontBold.getStringWidth(title) / 1000 * 12;
        content.beginText();
        content.newLineAtOffset((pageWidth - titleWidth) / 2, yPos[0]);
        content.showText(title);
        content.endText();
        yPos[0] -= 14;
        
        // Address
        content.setFont(fontRegular, 8);
        String addr1 = "123 Main Street";
        float addr1Width = fontRegular.getStringWidth(addr1) / 1000 * 8;
        content.beginText();
        content.newLineAtOffset((pageWidth - addr1Width) / 2, yPos[0]);
        content.showText(addr1);
        content.endText();
        yPos[0] -= 10;
        
        String addr2 = "Phnom Penh, Cambodia";
        float addr2Width = fontRegular.getStringWidth(addr2) / 1000 * 8;
        content.beginText();
        content.newLineAtOffset((pageWidth - addr2Width) / 2, yPos[0]);
        content.showText(addr2);
        content.endText();
        yPos[0] -= 10;
        
        String phone = "Tel: +855 12 345 678";
        float phoneWidth = fontRegular.getStringWidth(phone) / 1000 * 8;
        content.beginText();
        content.newLineAtOffset((pageWidth - phoneWidth) / 2, yPos[0]);
        content.showText(phone);
        content.endText();
        yPos[0] -= 15;
        
        // Line
        content.moveTo(margin, yPos[0]);
        content.lineTo(pageWidth - margin, yPos[0]);
        content.stroke();
        yPos[0] -= 10;

        // ===== DATE & TIME =====
        String dateTime = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(new Date());
        content.setFont(fontRegular, 8);
        content.beginText();
        content.newLineAtOffset(margin, yPos[0]);
        content.showText("Date: " + dateTime);
        content.endText();
        yPos[0] -= 12;

        // Receipt Number
        String receiptNo = "RCP" + System.currentTimeMillis();
        content.beginText();
        content.newLineAtOffset(margin, yPos[0]);
        content.showText("Receipt: " + receiptNo);
        content.endText();
        yPos[0] -= 15;

        // Line
        content.moveTo(margin, yPos[0]);
        content.lineTo(pageWidth - margin, yPos[0]);
        content.stroke();
        yPos[0] -= 10;

        // ===== TABLE HEADER =====
        content.setFont(fontBold, 9);
        content.beginText();
        content.newLineAtOffset(margin, yPos[0]);
        content.showText("Item");
        content.endText();

        content.beginText();
        content.newLineAtOffset(130, yPos[0]);
        content.showText("Qty");
        content.endText();

        content.beginText();
        content.newLineAtOffset(165, yPos[0]);
        content.showText("Price");
        content.endText();
        yPos[0] -= 12;

        // Line
        content.moveTo(margin, yPos[0]);
        content.lineTo(pageWidth - margin, yPos[0]);
        content.stroke();
        yPos[0] -= 8;

        // ===== ITEMS =====
        content.setFont(fontRegular, 8);
        double subtotal = 0;

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            String item = jTable1.getValueAt(i, 0).toString();
            String qty = jTable1.getValueAt(i, 1).toString();
            String price = jTable1.getValueAt(i, 2).toString();

            // Truncate long item names
            if (item.length() > 20) {
                item = item.substring(0, 17) + "...";
            }

            // Item name
            content.beginText();
            content.newLineAtOffset(margin, yPos[0]);
            content.showText(item);
            content.endText();

            // Quantity
            content.beginText();
            content.newLineAtOffset(135, yPos[0]);
            content.showText(qty);
            content.endText();

            // Price
            content.beginText();
            content.newLineAtOffset(160, yPos[0]);
            content.showText("$" + price);
            content.endText();

            yPos[0] -= 12;
            subtotal += Double.parseDouble(price);
        }

        yPos[0] -= 3;
        
        // Line
        content.moveTo(margin, yPos[0]);
        content.lineTo(pageWidth - margin, yPos[0]);
        content.stroke();
        yPos[0] -= 10;

        // ===== TOTALS =====
        double tax = subtotal * 0.039;
        double total = subtotal + tax;

        // Subtotal
        content.setFont(fontRegular, 9);
        content.beginText();
        content.newLineAtOffset(margin, yPos[0]);
        content.showText("Subtotal:");
        content.endText();
        content.beginText();
        content.newLineAtOffset(150, yPos[0]);
        content.showText(String.format("$ %.2f", subtotal));
        content.endText();
        yPos[0] -= 12;

        // Tax
        content.beginText();
        content.newLineAtOffset(margin, yPos[0]);
        content.showText("Tax (3.9%):");
        content.endText();
        content.beginText();
        content.newLineAtOffset(150, yPos[0]);
        content.showText(String.format("$ %.2f", tax));
        content.endText();
        yPos[0] -= 15;

        // Total
        content.setFont(fontBold, 11);
        content.beginText();
        content.newLineAtOffset(margin, yPos[0]);
        content.showText("TOTAL:");
        content.endText();
        content.beginText();
        content.newLineAtOffset(145, yPos[0]);
        content.showText(String.format("$ %.2f", total));
        content.endText();
        yPos[0] -= 15;

        // Line
        content.moveTo(margin, yPos[0]);
        content.lineTo(pageWidth - margin, yPos[0]);
        content.stroke();
        yPos[0] -= 10;

        // ===== PAYMENT INFO =====
        String paymentMethod = jcbopayment.getSelectedItem().toString();
        content.setFont(fontRegular, 8);
        content.beginText();
        content.newLineAtOffset(margin, yPos[0]);
        content.showText("Payment: " + paymentMethod);
        content.endText();
        yPos[0] -= 12;

        if (paymentMethod.equals("Cash")) {
            String cashPaid = jtxtDisplay.getText();
            String change = jtxtChange.getText();
            
            if (!cashPaid.isEmpty()) {
                content.beginText();
                content.newLineAtOffset(margin, yPos[0]);
                content.showText("Cash: " + cashPaid);
                content.endText();
                yPos[0] -= 12;
            }
            
            if (!change.isEmpty()) {
                content.beginText();
                content.newLineAtOffset(margin, yPos[0]);
                content.showText("Change: " + change);
                content.endText();
                yPos[0] -= 12;
            }
        }

        yPos[0] -= 5;
        
        // Line
        content.moveTo(margin, yPos[0]);
        content.lineTo(pageWidth - margin, yPos[0]);
        content.stroke();
        yPos[0] -= 15;

        // ===== FOOTER =====
        content.setFont(fontBold, 9);
        String thanks = "Thank You for Your Visit!";
        float thanksWidth = fontBold.getStringWidth(thanks) / 1000 * 9;
        content.beginText();
        content.newLineAtOffset((pageWidth - thanksWidth) / 2, yPos[0]);
        content.showText(thanks);
        content.endText();
        yPos[0] -= 12;
        
        content.setFont(fontRegular, 8);
        String comeAgain = "Please Come Again";
        float comeAgainWidth = fontRegular.getStringWidth(comeAgain) / 1000 * 8;
        content.beginText();
        content.newLineAtOffset((pageWidth - comeAgainWidth) / 2, yPos[0]);
        content.showText(comeAgain);
        content.endText();
        yPos[0] -= 12;
        
        String website = "www.amazonforestcafe.com";
        float websiteWidth = fontRegular.getStringWidth(website) / 1000 * 8;
        content.beginText();
        content.newLineAtOffset((pageWidth - websiteWidth) / 2, yPos[0]);
        content.showText(website);
        content.endText();

        content.close();
        doc.save(filePath);
        doc.close();

        JOptionPane.showMessageDialog(this, 
            "Receipt saved successfully!\n" + filePath,
            "Success",
            JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Error creating receipt: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }

    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        int response = JOptionPane.showConfirmDialog(
            this,
            "Confirm if you want to exit",
            "Point of Sales",
            JOptionPane.YES_NO_OPTION
    );

    if (response == JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPayActionPerformed
          DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    
    if (model.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "No items in cart!", 
            "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    String paymentMethod = jcbopayment.getSelectedItem().toString();
    double amountPaid = 0;
    double changeAmount = 0;
    double total = Double.parseDouble(jtxtTotal.getText().replace("$ ", ""));
    
    // Handle different payment methods
    if (paymentMethod.equals("Cash")) {
        if (jtxtDisplay.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter cash amount!", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        amountPaid = Double.parseDouble(jtxtDisplay.getText());
        String changeText = jtxtChange.getText().replace("$ ", "");
        changeAmount = changeText.isEmpty() ? 0 : Double.parseDouble(changeText);
        
        if (changeAmount < 0) {
            JOptionPane.showMessageDialog(this, "Insufficient cash amount!", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
    } else if (paymentMethod.equals("QR Code")) {
        // Show Bank Selection Dialog FIRST
        BankSelectionDialog bankDialog = new BankSelectionDialog(this);
        bankDialog.setVisible(true);
        
        String selectedBank = bankDialog.getSelectedBank();
        if (selectedBank == null) {
            // User cancelled bank selection
            return;
        }
        
        // Show QR Payment Dialog with selected bank
        QRPaymentDialog qrDialog = new QRPaymentDialog(this, total, selectedBank);
        qrDialog.setVisible(true);
        
        if (!qrDialog.isPaymentConfirmed()) {
            // User cancelled payment
            return;
        }
        
        amountPaid = total;
        changeAmount = 0;
        
    } else if (paymentMethod.equals("Visa Card") || paymentMethod.equals("Master Card")) {
        // Show Card Payment Dialog
        CardPaymentDialog cardDialog = new CardPaymentDialog(this, total, paymentMethod);
        cardDialog.setVisible(true);
        
        if (!cardDialog.isPaymentConfirmed()) {
            // User cancelled payment
            return;
        }
        
        amountPaid = total;
        changeAmount = 0;
        
    } else {
        // Fallback for any other payment methods
        int confirm = JOptionPane.showConfirmDialog(this, 
            String.format("Process %s payment of $ %.2f?", paymentMethod, total),
            "Confirm Payment", 
            JOptionPane.YES_NO_OPTION);
        
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        amountPaid = total;
        changeAmount = 0;
    }
    
    try {
        int orderId = orderManager.saveOrder(model, paymentMethod, 
                                            amountPaid, changeAmount);
        JOptionPane.showMessageDialog(this, 
            "Order completed successfully!\nOrder ID: " + orderId, 
            "Success", JOptionPane.INFORMATION_MESSAGE);
        
        // Reset form
        model.setRowCount(0);
        jtxtSubTotal.setText("");
        jtxtTax.setText("");
        jtxtTotal.setText("");
        jtxtDisplay.setText("");
        jtxtChange.setText("");
        jtxtBarCode.setText("");
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, 
            "Error saving order: " + e.getMessage(), 
            "Database Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }  
    }//GEN-LAST:event_jbtnPayActionPerformed
    
    private void jcbopaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbopaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbopaymentActionPerformed

    private void jbtnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDashboardActionPerformed
                                          
    DashboardPanel dashboard = new DashboardPanel();
    dashboard.setVisible(true);
  
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnDashboardActionPerformed
     
    private JFrame frame;
    /**
     * @param args the command line arguments
     */

    

    public static void main(String[] args) {

           try {
        FlatLightLaf.setup();
    } catch (Exception ex) {
        System.err.println("Failed to initialize FlatLaf.");
    }

    java.awt.EventQueue.invokeLater(() -> {
        new LoginScreen().setVisible(true);
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtnicelemontea;
    private javax.swing.JButton btnIceAmericano;
    private javax.swing.JButton hotMatchalatte;
    private javax.swing.JButton hotlatte;
    private javax.swing.JButton icecoffee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnChocolateCake;
    private javax.swing.JButton jbtnDashboard;
    private javax.swing.JButton jbtnDot;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnFriesChicken;
    private javax.swing.JButton jbtnHamBurger;
    private javax.swing.JButton jbtnIceMatchaLatte;
    private javax.swing.JButton jbtnLemonea;
    private javax.swing.JButton jbtnMangoFrape;
    private javax.swing.JButton jbtnNoodle;
    private javax.swing.JButton jbtnPay;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnPudding;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnRiceWithPork;
    private javax.swing.JButton jbtnStrawberryFrape;
    private javax.swing.JButton jbtnTiramisu;
    private javax.swing.JButton jbtnblueBerrycake;
    private javax.swing.JButton jbtncakeroll;
    private javax.swing.JButton jbtncaramaldrink;
    private javax.swing.JButton jbtnjaozi;
    private javax.swing.JComboBox<String> jcbopayment;
    private javax.swing.JLabel jlblDate;
    private javax.swing.JTextField jtxtBarCode;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
